"""Build UI subsets while retaining the original fonts for arbitrary place/plan names.

Requires fonttools and brotli. Run from any directory; outputs are deterministic.
"""
from pathlib import Path
import re
from fontTools import subset
from fontTools.ttLib import TTFont

root = Path(__file__).resolve().parents[1]
sources = [root / 'index.html', root / 'tokens.css', root / 'css/app.css', *sorted((root / 'js').rglob('*.js'))]
text = ''.join(path.read_text(encoding='utf-8') for path in sources if 'vendor' not in path.parts) + '年月日時分秒日月火水木金土曜午前午後−＋'
characters = set(map(ord, text)) | set(range(0x20, 0x100)) | set(range(0x3000, 0x3100)) | set(range(0xff00, 0xfff0))
characters.update(int(value, 16) for value in re.findall(r'\\u([0-9a-fA-F]{4})', text))
faces = []
def unicode_ranges(values):
    runs = []
    for value in sorted(values):
        if runs and value == runs[-1][1] + 1:
            runs[-1][1] = value
        else:
            runs.append([value, value])
    return ','.join(f'U+{start:X}' + (f'-{end:X}' if end != start else '') for start, end in runs)

for weight, name in [('400', 'Regular'), ('600 800', 'SemiBold')]:
    original = f'IBMPlexSansJP-{name}.woff2'
    filename = f'IBMPlexSansJP-{name}-ui.woff2'
    font = TTFont(root / 'assets/fonts' / original)
    cmap = set(font.getBestCmap())
    supported = sorted(characters & cmap)
    fallback_ranges = unicode_ranges(cmap - characters)
    options = subset.Options()
    options.flavor = 'woff2'
    options.recalc_timestamp = False
    sub = subset.Subsetter(options=options)
    sub.populate(unicodes=supported)
    sub.subset(font)
    font.save(root / 'assets/fonts' / filename)
    ranges = unicode_ranges(supported)
    faces.append(f'@font-face {{ font-family: "IBM Plex Sans JP"; src: url("../assets/fonts/{original}") format("woff2"); font-style: normal; font-weight: {weight}; font-display: swap; unicode-range: {fallback_ranges}; }}')
    faces.append(f'@font-face {{ font-family: "IBM Plex Sans JP"; src: url("../assets/fonts/{filename}") format("woff2"); font-style: normal; font-weight: {weight}; font-display: swap; unicode-range: {ranges}; }}')
    print(f'{filename}: {(root / "assets/fonts" / filename).stat().st_size:,} bytes, {len(supported)} codepoints')
(root / 'css/ui-fonts.css').write_text('/* Generated by tools/subset-fonts.py. Original fonts and OFL license retained. */\n' + '\n'.join(faces) + '\n', encoding='utf-8')
